### PR TITLE
Add visual monitor

### PR DESCRIPTION
**Pull request by amitaibu**
#1

### CODE REVIEW

**Comment by kellybell** [comment]
Loving it, Amitai! Great work!

**Comment by amitaibu** [comment]
@kellybell Thanks! Next I expect to see you using it ;)

**Comment by kellybell** [comment]
Watching closely for now, but as soon as we can, we will be! We are happily
using your RESTful API as well.

I watch your work very closely, Amitai (I know I'm not alone), and am a
huge fan. Your work is the future of Drupal Thank you.

Kelly Bell
Founder and CTO
Gotham City Drupal
917.446.1555

On Jul 17, 2015, at 10:13, Amitai Burstein notifications@github.com wrote:

@kellybell https://github.com/kellybell Thanks! Next I expect to see you
using it ;)

**Comment by amitaibu** [comment]
:blush:

**Pull request merged**
